apiVersion: v1
kind: Secret
metadata:
  name: azure-secret-akkc
type: Opaque
# stringData: used to store secret data in unencoded form that is plain text.
#     azurestorageaccountname: akkcdevddddstgtest
#     azurestorageaccountkey: pyDPaqdddxsyuu66dd1YfnyWuWbbddmBqRvCpCnrxbxYaozdpsDPX9EgcmnoFAo9UcAIcDkn1zfiZ8yR8key+ASts0Sq9A==

data:   # Jab hum data ka use karte hn tab humko base64 me encode karna padta hai.
  azurestorageaccountname: c3dRddnddGVzdGRldjddsdAxYWtrYw==     # echo anoopsa | base64 -d
  azurestorageaccountkey: cHlEUddGFxeHN5dddXU2NjFZZm55V3VXYmsdJtQnddFSdkNwQ25yeGJ4WWFvenBzRFBYOUVdwnY21ub0ZBddbzlVY0FJYrtrds0RrbjF6ZmlaOHlSOGtleStBU3RzMFNxOUE9PQ==

