apiVersion: v1
kind: Secret
metadata:
  name: azure-secret-akkc
type: Opaque
# stringData: used to store secret data in unencoded form that is plain text.
#     azurestorageaccountname: akkcdevstgtest
#     azurestorageaccountkey: pyDPaqxsyuu661YfnyWuWbbmBqRvCpCnrxbxYaozpsDPX9EgcmnoFAo9UcAIcDkn1zfiZ8yR8key+ASts0Sq9A==

data:   # Jab hum data ka use karte hn tab humko base64 me encode karna padta hai.
  azurestorageaccountname: c3RndGVzdGRldjAxYWtrYw==     # echo anoopsa | base64 -d
  azurestorageaccountkey: cHlEUGFxeHN5dXU2NjFZZm55V3VXYmJtQnFSdkNwQ25yeGJ4WWFvenBzRFBYOUVnY21ub0ZBbzlVY0FJY0RrbjF6ZmlaOHlSOGtleStBU3RzMFNxOUE9PQ==

