apiVersion: v1
kind: Namespace
metadata:
  name: akkc-main-app
  labels:
    gateway-access: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: akkc-app1
  labels:
    gateway-access: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: akkc-app2
  labels:
    gateway-access: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: akkc-gateway