apiVersion: alb.networking.azure.io/v1
kind: ApplicationLoadBalancer
metadata:
  name: alb-test
  namespace: agc-test
spec:
  associations:
  - /subscriptions/b8e77924-89da-41ce-8257-846989faab77/resourceGroups/MC_aks-gateway-api-test_aks-gateway-api_koreacentral/providers/Microsoft.Network/virtualNetworks/aks-vnet-10218664/subnets/alb-subnet