apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: polinux/stress
        command:
        - stress
        args:
        - "--cpu"
        - "2"
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "256M"
        - "--timeout"
        - "600s"