apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - name: app-container
    image: nginx:latest
    ports:
      - containerPort: 80

    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
        
    volumeMounts:
      - mountPath: /usr/share/data
        name: temp-storage

  volumes:
    - name: temp-storage
      emptyDir: {}

