apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: nginx:alpine

          volumeMounts:
            - name: secret-volume
              mountPath: /etc/mysecret

      volumes:
        - name: secret-volume
          secret:
            secretName: db-secret