apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-mac-storage   # must match PV
  resources:
    requests:
      storage: 1Gi