apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: configmap-env

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine

          ports:
            - containerPort: 80

          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: APP_NAME

            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: ENVIRONMENT

            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: MESSAGE