apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
data:
  MYSQL_DATABASE: ZGV2b3BzCg== # base64 encoded for 'devops'
  MYSQL_ROOT_PASSWORD: cm9vdAo= # base64 encoded for 'root'