apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: app-container
    image: nginx:latest
    ports:
      - containerPort: 80

    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
        
    volumeMounts:
    - mountPath: /data
      name: my-volume

  volumes:
  - name: my-volume
    hostPath:
      path: /Users/amitkumar/Documents/MLOps
      type: Directory
