apiVersion: v1
kind: Secret
metadata:
  name: cluster-admin-sa-token
  namespace: cicd-dev
  annotations:
    kubernetes.io/service-account.name: cluster-admin-sa
type: kubernetes.io/service-account-token