# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: azure-kv
#   namespace: akkc

# spec:
#   provider: azure

#   parameters:
#     clientID: "95251e3e-a73e-42c9-b84a-d3c1b85e6fc0"
#     keyvaultName: "kv-sp-to-mi"
#     tenantId: "84918198-1cc9-4d1b-b0fa-0235ccf4d609"

#     objects: |
#       array:
#         - |
#           objectName: love
#           objectType: secret
#         - |
#           objectName: hate
#           objectType: secret

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: azure-kv
  namespace: akkc

spec:
  provider: azure

  parameters:
    clientID: "95251e3e-a73e-42c9-b84a-d3c1b85e6fc0"
    keyvaultName: "kv-sp-to-mi"
    tenantId: "84918198-1cc9-4d1b-b0fa-0235ccf4d609"

    objects: |
      array:
        - |
          objectName: love
          objectType: secret
        - |
          objectName: hate
          objectType: secret

  secretObjects:
    - secretName: kv-secret
      type: Opaque
      data:
        - objectName: love
          key: LOVE_SECRET
        - objectName: hate
          key: HATE_SECRET