apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: nginx:alpine

          envFrom:
            - secretRef:
                name: db-secret

# Kubernetes automatically Secret ki saari keys ko container ke environment variables bana dega. env se hame sabhi kyes ko pass karna pad rha tha.